import { type ProjectSnapshot, projectSnapshotSchema, schemaVersion } from "@takeboard/contracts";

const createdAt = "2026-08-13T03:30:00.000Z";
const hash = (character: string) => character.repeat(64);
const uuid = (suffix: string) => `018f47a0-2c91-7a4f-a812-${suffix.padStart(12, "0")}`;
const id = (prefix: string, suffix: string) => `${prefix}_${uuid(suffix)}`;

export const demoIds = {
  project: id("project", "1"),
  scene: id("scene", "2"),
  script: id("text", "3"),
  direction: id("text", "4"),
  character: id("entity", "5"),
  portrait: id("asset", "6"),
  location: id("asset", "7"),
  shotA: id("shot", "8"),
  shotB: id("shot", "9"),
  shotC: id("shot", "a"),
  itemScript: id("canvas_item", "b"),
  itemCharacter: id("canvas_item", "c"),
  itemLocation: id("canvas_item", "d"),
  itemShotA: id("canvas_item", "e"),
  itemShotB: id("canvas_item", "f"),
  itemShotC: id("canvas_item", "10"),
} as const;

export function createDemoSnapshot(): ProjectSnapshot {
  return projectSnapshotSchema.parse({
    schemaVersion,
    exportedAt: createdAt,
    project: {
      id: demoIds.project,
      schemaVersion,
      title: "雾港来信",
      defaultAspectRatio: "16:9",
      createdAt,
      updatedAt: createdAt,
    },
    scenes: [
      {
        id: demoIds.scene,
        projectId: demoIds.project,
        label: "SC-01",
        title: "清晨的旧渡口",
        order: 0,
        createdAt,
        updatedAt: createdAt,
      },
    ],
    textItems: [
      {
        id: demoIds.script,
        projectId: demoIds.project,
        sceneId: demoIds.scene,
        kind: "script",
        title: "场景剧本",
        body: "天刚亮，林夏独自走到废弃渡口。雾里传来旧船的汽笛声，她在长椅下发现一封没有署名的信。",
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: demoIds.direction,
        projectId: demoIds.project,
        sceneId: demoIds.scene,
        kind: "direction_note",
        title: "视觉方向",
        body: "冷青灰、潮湿空气、克制的悬疑感。人物脸部保持自然，避免过度磨皮。",
        createdAt,
        updatedAt: createdAt,
      },
    ],
    entities: [
      {
        id: demoIds.character,
        projectId: demoIds.project,
        kind: "character",
        name: "林夏",
        description: "27 岁，短发，深色风衣。表面冷静，发现信件时有一瞬间迟疑。",
        referenceAssetIds: [demoIds.portrait],
        createdAt,
        updatedAt: createdAt,
      },
    ],
    assets: [
      {
        id: demoIds.portrait,
        projectId: demoIds.project,
        mediaType: "image",
        originalName: "lin-xia-reference.jpg",
        mimeType: "image/jpeg",
        byteSize: 284_000,
        sha256: hash("a"),
        storagePath: `assets/originals/${hash("a")}.jpg`,
        proxyPath: `assets/proxies/${hash("a")}.jpg`,
        width: null,
        height: null,
        customTags: ["角色定妆"],
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: demoIds.location,
        projectId: demoIds.project,
        mediaType: "image",
        originalName: "foggy-ferry-location.jpg",
        mimeType: "image/jpeg",
        byteSize: 412_000,
        sha256: hash("b"),
        storagePath: `assets/originals/${hash("b")}.jpg`,
        proxyPath: `assets/proxies/${hash("b")}.jpg`,
        width: null,
        height: null,
        customTags: ["场景氛围"],
        createdAt,
        updatedAt: createdAt,
      },
    ],
    shots: [
      {
        id: demoIds.shotA,
        projectId: demoIds.project,
        sceneId: demoIds.scene,
        label: "S001",
        order: 0,
        intent: "大全景建立雾港环境，林夏从画面右侧进入，远处渡船轮廓若隐若现。",
        durationSeconds: 4,
        aspectRatio: "16:9",
        workflowPath: "Kino/Kino_Wan22_I2V.json",
        status: "draft",
        approvedTakeId: null,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: demoIds.shotB,
        projectId: demoIds.project,
        sceneId: demoIds.scene,
        label: "S002",
        order: 1,
        intent: "中近景跟拍林夏走向长椅，风吹动衣摆，她听见汽笛后短暂停顿。",
        durationSeconds: 5,
        aspectRatio: "16:9",
        workflowPath: "Kino/Kino_Wan22_FLF2V.json",
        status: "draft",
        approvedTakeId: null,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: demoIds.shotC,
        projectId: demoIds.project,
        sceneId: demoIds.scene,
        label: "S003",
        order: 2,
        intent: "信件特写，潮湿纸面上只有一句：别登上今天的船。",
        durationSeconds: 3,
        aspectRatio: "16:9",
        workflowPath: "Kino/Kino_MinimaxH3_T2V.json",
        status: "draft",
        approvedTakeId: null,
        createdAt,
        updatedAt: createdAt,
      },
    ],
    runs: [],
    takes: [],
    approvals: [],
    canvasItems: [
      {
        id: demoIds.itemScript,
        sceneId: demoIds.scene,
        refType: "text",
        refId: demoIds.script,
        x: 70,
        y: 80,
        width: 280,
        height: 190,
        zIndex: 1,
        parentGroupId: null,
        collapsed: false,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: demoIds.itemCharacter,
        sceneId: demoIds.scene,
        refType: "entity",
        refId: demoIds.character,
        x: 70,
        y: 340,
        width: 280,
        height: 210,
        zIndex: 1,
        parentGroupId: null,
        collapsed: false,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: demoIds.itemLocation,
        sceneId: demoIds.scene,
        refType: "asset",
        refId: demoIds.location,
        x: 70,
        y: 620,
        width: 280,
        height: 190,
        zIndex: 1,
        parentGroupId: null,
        collapsed: false,
        createdAt,
        updatedAt: createdAt,
      },
      ...[demoIds.shotA, demoIds.shotB, demoIds.shotC].map((shotId, index) => ({
        id: [demoIds.itemShotA, demoIds.itemShotB, demoIds.itemShotC][index],
        sceneId: demoIds.scene,
        refType: "shot" as const,
        refId: shotId,
        x: 520,
        y: 90 + index * 250,
        width: 330,
        height: 190,
        zIndex: 2,
        parentGroupId: null,
        collapsed: false,
        createdAt,
        updatedAt: createdAt,
      })),
    ],
    canvasEdges: [
      ...[demoIds.itemShotA, demoIds.itemShotB, demoIds.itemShotC].map((targetItemId, index) => ({
        id: id("canvas_edge", (20 + index).toString(16)),
        sceneId: demoIds.scene,
        sourceItemId: demoIds.itemScript,
        targetItemId,
        relation: "reference" as const,
        targetSlot: null,
        targetSlotIndex: 0,
        runId: null,
        immutable: false,
        createdAt,
        updatedAt: createdAt,
      })),
      ...[demoIds.itemShotA, demoIds.itemShotB].map((targetItemId, index) => ({
        id: id("canvas_edge", (30 + index).toString(16)),
        sceneId: demoIds.scene,
        sourceItemId: index === 0 ? demoIds.itemLocation : demoIds.itemCharacter,
        targetItemId,
        relation: "reference" as const,
        targetSlot: null,
        targetSlotIndex: 0,
        runId: null,
        immutable: false,
        createdAt,
        updatedAt: createdAt,
      })),
    ],
  });
}
