#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
unit_template="$repo_dir/deploy/systemd/takeboard.service.in"
config_dir=${TAKEBOARD_CONFIG_DIR:-$HOME/.config/takeboard}
unit_dir=${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user
data_root=${TAKEBOARD_DATA_ROOT:-$HOME/TakeBoardData}
node_bin=$(command -v node || true)
skip_build=0

if [[ ${1:-} == --skip-build ]]; then
  skip_build=1
elif [[ $# -gt 0 ]]; then
  echo "Usage: $0 [--skip-build]" >&2
  exit 2
fi

if [[ -z $node_bin ]]; then
  echo "Node.js is required." >&2
  exit 1
fi
if command -v pnpm >/dev/null 2>&1; then
  package_manager=(pnpm)
elif command -v corepack >/dev/null 2>&1; then
  package_manager=(corepack pnpm)
else
  echo "pnpm or Corepack is required." >&2
  exit 1
fi
validate_unit_value() {
  local label=$1
  local value=$2
  if [[ $value == *$'\n'* || $value == *'"'* || $value == *'%'* ]]; then
    echo "${label} contains a character unsupported by the systemd template: ${value}" >&2
    exit 1
  fi
}

sed_replacement() {
  local value=$1
  value=${value//\\/\\\\}
  value=${value//&/\\&}
  value=${value//|/\\|}
  printf '%s' "$value"
}

write_env_value() {
  local key=$1
  local value=$2
  if [[ $value == *$'\n'* ]]; then
    echo "${key} contains an unsupported newline." >&2
    exit 1
  fi
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '%s="%s"\n' "$key" "$value"
}

validate_unit_value "Repository path" "$repo_dir"
validate_unit_value "Node.js path" "$node_bin"
validate_unit_value "Data path" "$data_root"
validate_unit_value "Configuration path" "$config_dir"

if ((skip_build == 0)); then
  cd "$repo_dir"
  "${package_manager[@]}" install --frozen-lockfile
  "${package_manager[@]}" verify
fi

mkdir -p "$config_dir" "$unit_dir" "$data_root"
if [[ ! -f $config_dir/env ]]; then
  {
    echo '# Generated by TakeBoard. Edit values, then run: ./scripts/takeboard restart'
    write_env_value COMFY_URL "${COMFY_URL:-http://127.0.0.1:8188}"
    write_env_value COMFY_EDITOR_URL "${COMFY_EDITOR_URL:-http://127.0.0.1:48188}"
    write_env_value COMFY_INPUT_ROOT "${COMFY_INPUT_ROOT:-}"
    write_env_value COMFY_OUTPUT_ROOT "${COMFY_OUTPUT_ROOT:-}"
  } > "$config_dir/env"
  chmod 600 "$config_dir/env"
  echo "Created ${config_dir}/env"
fi

repo_unit_value=$(sed_replacement "$repo_dir")
node_unit_value=$(sed_replacement "$node_bin")
data_unit_value=$(sed_replacement "$data_root")
config_unit_value=$(sed_replacement "$config_dir")
sed \
  -e "s|@REPO_DIR@|$repo_unit_value|g" \
  -e "s|@NODE_BIN@|$node_unit_value|g" \
  -e "s|@DATA_ROOT@|$data_unit_value|g" \
  -e "s|@CONFIG_DIR@|$config_unit_value|g" \
  "$unit_template" > "$unit_dir/takeboard.service"

systemctl --user daemon-reload
systemctl --user enable takeboard.service
systemctl --user restart takeboard.service

attempt=0
until curl --fail --silent --max-time 3 http://127.0.0.1:48120/api/health >/dev/null; do
  attempt=$((attempt + 1))
  if ((attempt >= 30)); then
    systemctl --user --no-pager --full status takeboard.service || true
    echo "TakeBoard did not become healthy within 30 seconds." >&2
    exit 1
  fi
  sleep 1
done

echo "TakeBoard service installed and healthy."
echo "Local URL: http://127.0.0.1:48120"
echo "Configuration: ${config_dir}/env"
