#!/usr/bin/env bash
set -euo pipefail
umask 077

repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
unit_template="$repo_dir/deploy/systemd/takeboard.service.in"
config_dir=${TAKEBOARD_CONFIG_DIR:-$HOME/.config/takeboard}
unit_dir=${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user
data_root=${TAKEBOARD_DATA_ROOT:-$HOME/TakeBoardData}
node_bin=$(command -v node || true)
skip_build=0

if [[ ${1:-} == --skip-build ]]; then
  skip_build=1
elif [[ $# -gt 0 ]]; then
  echo "Usage: $0 [--skip-build]" >&2
  exit 2
fi

if [[ $(uname -s) != Linux ]] || ! command -v systemctl >/dev/null 2>&1; then
  echo "The stable service installer requires Linux with systemd." >&2
  echo "On macOS or Windows, use the development command or install TakeBoard with your native service manager." >&2
  exit 1
fi
if ! systemctl --user show-environment >/dev/null 2>&1; then
  echo "A working systemd user session is required." >&2
  echo "Log in normally, or enable user lingering before installing TakeBoard." >&2
  exit 1
fi

if [[ -z $node_bin ]]; then
  echo "Node.js is required." >&2
  exit 1
fi
if [[ $data_root == "~" ]]; then
  data_root=$HOME
elif [[ $data_root == "~/"* ]]; then
  data_root="$HOME/${data_root:2}"
fi
data_root=$("$node_bin" -e 'process.stdout.write(require("node:path").resolve(process.argv[1]))' "$data_root")
if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required for the service health check." >&2
  exit 1
fi
if command -v pnpm >/dev/null 2>&1; then
  package_manager=(pnpm)
elif command -v corepack >/dev/null 2>&1; then
  package_manager=(corepack pnpm)
else
  echo "pnpm or Corepack is required." >&2
  exit 1
fi
validate_unit_value() {
  local label=$1
  local value=$2
  if [[ $value == *$'\n'* || $value == *'"'* || $value == *'%'* ]]; then
    echo "${label} contains a character unsupported by the systemd template: ${value}" >&2
    exit 1
  fi
}

sed_replacement() {
  local value=$1
  value=${value//\\/\\\\}
  value=${value//&/\\&}
  value=${value//|/\\|}
  printf '%s' "$value"
}

write_env_value() {
  local key=$1
  local value=$2
  if [[ $value == *$'\n'* ]]; then
    echo "${key} contains an unsupported newline." >&2
    exit 1
  fi
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '%s="%s"\n' "$key" "$value"
}

validate_unit_value "Repository path" "$repo_dir"
validate_unit_value "Node.js path" "$node_bin"
validate_unit_value "Data path" "$data_root"
validate_unit_value "Configuration path" "$config_dir"

if ((skip_build == 0)); then
  cd "$repo_dir"
  "${package_manager[@]}" install --frozen-lockfile
  "${package_manager[@]}" verify
fi

mkdir -p "$config_dir" "$unit_dir" "$data_root"
instance_id_file="$data_root/.takeboard-instance-id"
if [[ ! -f $instance_id_file ]]; then
  "$node_bin" -e 'process.stdout.write(require("node:crypto").randomUUID() + "\n")' > "$instance_id_file"
fi
chmod 600 "$instance_id_file"
instance_id=$(tr -d '\r\n' < "$instance_id_file")
if [[ ! $instance_id =~ ^[A-Za-z0-9-]{10,100}$ ]]; then
  echo "Invalid TakeBoard instance identity: ${instance_id_file}" >&2
  exit 1
fi
validate_unit_value "Instance ID" "$instance_id"
if [[ ! -f $config_dir/env ]]; then
  {
    echo '# Generated by TakeBoard. Edit values, then run: ./scripts/takeboard restart'
    write_env_value COMFY_URL "${COMFY_URL:-http://127.0.0.1:8188}"
    write_env_value COMFY_EDITOR_URL "${COMFY_EDITOR_URL:-http://127.0.0.1:48188}"
    write_env_value COMFY_INPUT_ROOT "${COMFY_INPUT_ROOT:-}"
    write_env_value COMFY_OUTPUT_ROOT "${COMFY_OUTPUT_ROOT:-}"
    write_env_value COMFY_LAUNCH_PROVIDER "${COMFY_LAUNCH_PROVIDER:-auto}"
    write_env_value COMFY_START_SERVICE "${COMFY_START_SERVICE:-takeboard-comfy.service}"
    write_env_value COMFY_LAUNCHD_LABEL "${COMFY_LAUNCHD_LABEL:-}"
    write_env_value COMFY_WINDOWS_SERVICE "${COMFY_WINDOWS_SERVICE:-}"
    write_env_value COMFY_START_EXECUTABLE "${COMFY_START_EXECUTABLE:-}"
    write_env_value COMFY_START_ARGS_JSON "${COMFY_START_ARGS_JSON:-[]}"
    write_env_value COMFY_START_CWD "${COMFY_START_CWD:-}"
    write_env_value COMFY_START_PID_FILE "${COMFY_START_PID_FILE:-}"
    write_env_value COMFY_ACCELERATOR "${COMFY_ACCELERATOR:-auto}"
    write_env_value COMFY_GPU_INDEX "${COMFY_GPU_INDEX:-0}"
    write_env_value COMFY_MIN_FREE_RAM_GB "${COMFY_MIN_FREE_RAM_GB:-6}"
    write_env_value COMFY_MIN_FREE_VRAM_GB "${COMFY_MIN_FREE_VRAM_GB:-4}"
    write_env_value COMFY_MAX_GPU_UTILIZATION "${COMFY_MAX_GPU_UTILIZATION:-85}"
  } > "$config_dir/env"
  echo "Created ${config_dir}/env"
fi
chmod 600 "$config_dir/env"

repo_unit_value=$(sed_replacement "$repo_dir")
node_unit_value=$(sed_replacement "$node_bin")
data_unit_value=$(sed_replacement "$data_root")
config_unit_value=$(sed_replacement "$config_dir")
instance_unit_value=$(sed_replacement "$instance_id")
sed \
  -e "s|@REPO_DIR@|$repo_unit_value|g" \
  -e "s|@NODE_BIN@|$node_unit_value|g" \
  -e "s|@DATA_ROOT@|$data_unit_value|g" \
  -e "s|@CONFIG_DIR@|$config_unit_value|g" \
  -e "s|@INSTANCE_ID@|$instance_unit_value|g" \
  "$unit_template" > "$unit_dir/takeboard.service"

systemctl --user daemon-reload
systemctl --user enable takeboard.service
systemctl --user restart takeboard.service

attempt=0
until curl --fail --silent --max-time 3 http://127.0.0.1:48120/api/health >/dev/null; do
  attempt=$((attempt + 1))
  if ((attempt >= 30)); then
    systemctl --user --no-pager --full status takeboard.service || true
    echo "TakeBoard did not become healthy within 30 seconds." >&2
    exit 1
  fi
  sleep 1
done

echo "TakeBoard service installed and healthy."
echo "Local URL: http://127.0.0.1:48120"
echo "Configuration: ${config_dir}/env"
